name: data-science-stack
summary: ML development and experimentation environment manager
description: |
     The DSS is a tool that allows workstations users to deploy
     and manage development and experimentation environments
     in systems with GPU support.
adopt-info: data-science-stack-version
base: core22
confinement: strict
architectures:
  - build-on: [amd64]
    build-for: [all]

apps:
  dss:
    command: bin/dss
    plugs:
      - home
      - network
parts:
  data-science-stack-version:
    plugin: nil
    source: .
    override-pull: |
      craftctl default
      # Pull the version from setup.cfg, parsing the value after 
      # the '=' and truncating any whitespace
      CODE_VERSION=$(grep version setup.cfg)
      CODE_VERSION=$(echo ${CODE_VERSION#*=} | tr -d ' ')
      COMMIT_HASH=$(git rev-parse HEAD)
      VERSION=${CODE_VERSION}-${COMMIT_HASH}
      # version field has max length of 32 characters
      craftctl set version=${VERSION:0:32}

  data-science-stack:
    plugin: python
    source: .

