name: data-science-stack
summary: ML development and experimentation environment manager
description: |
     The DSS is a tool that allows workstations users to deploy
     and manage development and experimentation environments
     in systems with GPU support.
adopt-info: data-science-stack
base: core22
confinement: strict
architectures:
  - build-on: amd64

plugs:
  dot-dss-config:
    interface: personal-files
    read:
      - $HOME/.dss/config
apps:
  dss:
    command: bin/dss
    plugs:
      - home
      - network
parts:
  data-science-stack:
    plugin: python
    source: .
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
