---
apiVersion: v1
kind: Namespace
metadata:
  name: dss

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: dss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: dss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow-container
          image: ubuntu/mlflow:2.1.1_1.0-22.04
          args: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-pvc
              mountPath: /mlruns
      volumes:
        - name: mlflow-pvc
          persistentVolumeClaim:
            claimName: mlflow-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-svc
  namespace: dss
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
