---
apiVersion: v1
kind: Namespace
metadata:
  name: dss
  labels:
    app.kubernetes.io/part-of: dss

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow
  namespace: dss
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: dss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: dss
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: dss
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/part-of: dss
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow
        app.kubernetes.io/part-of: dss
    spec:
      containers:
        - name: mlflow
          image: ubuntu/mlflow:2.1.1_1.0-22.04
          args: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow
              mountPath: /mlruns
      volumes:
        - name: mlflow
          persistentVolumeClaim:
            claimName: mlflow

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: dss
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: dss
spec:
  selector:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: dss
  ports:
    - protocol: TCP
      port: 5000
