name: "tagged-release"

on:
  push:
    tags:
      - "*"

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-22.04"
    needs: tests

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Validate version in tag
        # check that version matches Semantic Versioning
        run: |
          if ! [[ ${{ github.ref_name }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$|^[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$ ]]
          then
            echo "Tag has incorrect format. Valid formats are X.X.X or X.X.X.devX where X is any digit"
            exit 1
          fi
      - name: Check tag and PyPi version
        # Compare version of the tag with the latest PyPi published version
        run: |
          packages=$(pip index versions data-science-stack)
          latest=$(echo $packages| grep -oP '(?<=\().+?(?=\))')
          dpkg --compare-versions ${{ github.ref_name }} gt $latest
          if [ $? -ne 0 ]; then
            echo "Version in git tag must be greater than already published"
            exit $?
          fi

      - name: Compare git tag and version in setup.cfg
        run: |
          versionInFile=$(grep "^version = " setup.cfg | cut -d "=" -f 2 | tr -d '[:space:]')
          if [ $versionInFile != ${{ github.ref_name }} ]; then
            echo "Version in file does not match version in git tag"
            exit 1
          fi

      - name: Build package
        run: python -m build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            dist/*
